const i18Obj = {
    'en': {
      'unit': 'Portfolio',
      'language-skills': 'Skills',
      'language-portfolio': 'Portfolio',
      'language-video': 'Video',
      'language-price': 'Price',
      'language-contacts': 'Contacts',
      'language-hero-title': 'Alexa Rise',
      'language-hero-text': 'Save sincere emotions, romantic feelings and happy moments of life together with professional photographer Alexa Rise',
      'language-hire': 'Hire me',
      'language-skill-title-1': 'Digital photography',
      'language-skill-text-1': 'High-quality photos in the studio and on the nature',
      'language-skill-title-2': 'Video shooting',
      'language-skill-text-2': 'Capture your moments so that they always stay with you',
      'language-skill-title-3': 'Retouch',
      'language-skill-text-3': 'I strive to make photography surpass reality',
      'language-skill-title-4': 'Audio',
      'language-skill-text-4': 'Professional sounds recording for video, advertising, portfolio',
      'language-winter': 'Winter',
      'language-spring': 'Spring',
      'language-summer': 'Summer',
      'language-autumn': 'Autumn',
      'language-price-description-1-span-1': 'One location',
      'language-price-description-1-span-2': '120 photos in color',
      'language-price-description-1-span-3': '12 photos in retouch',
      'language-price-description-1-span-4': 'Readiness 2-3 weeks',
      'language-price-description-1-span-5': 'Make up, visage',
      'language-price-description-2-span-1': 'One or two locations',
      'language-price-description-2-span-2': '200 photos in color',
      'language-price-description-2-span-3': '20 photos in retouch',
      'language-price-description-2-span-4': 'Readiness 1-2 weeks',
      'language-price-description-2-span-5': 'Make up, visage',
      'language-price-description-3-span-1': 'Three locations or more',
      'language-price-description-3-span-2': '300 photos in color',
      'language-price-description-3-span-3': '50 photos in retouch',
      'language-price-description-3-span-4': 'Readiness 1 week',
      'language-price-description-3-span-5': 'Make up, visage, hairstyle',
      'language-order': 'Order shooting',
      'language-contact-me': 'Contact me',
      'language-send-message': 'Send message',
      'language-mail' : 'E-mail',
      'language-phone': 'Phone',
      'language-message' : 'Message',

    },
    'ru': {
      'unit': 'Портфолио',
      'language-skills': 'Навыки',
      'language-portfolio': 'Портфолио',
      'language-video': 'Видео',
      'language-price': 'Цены',
      'language-contacts': 'Контакты',
      'language-hero-title': 'Алекса Райс',
      'language-hero-text': 'Сохраните искренние эмоции, романтические переживания и счастливые моменты жизни вместе с профессиональным фотографом',
      'language-hire': 'Пригласить',
      'language-skill-title-1': 'Фотография',
      'language-skill-text-1': 'Высококачественные фото в студии и на природе',
      'language-skill-title-2': 'Видеосъемка',
      'language-skill-text-2': 'Запечатлите лучшие моменты, чтобы они всегда оставались с вами',
      'language-skill-title-3': 'Ретушь',
      'language-skill-text-3': 'Я стремлюсь к тому, чтобы фотография превосходила реальность',
      'language-skill-title-4': 'Звук',
      'language-skill-text-4': 'Профессиональная запись звука для видео, рекламы, портфолио',
      'language-winter': 'Зима',
      'language-spring': 'Весна',
      'language-summer': 'Лето',
      'language-autumn': 'Осень',
      'language-price-description-1-span-1': 'Одна локация',
      'language-price-description-1-span-2': '120 цветных фото',
      'language-price-description-1-span-3': '12 отретушированных фото',
      'language-price-description-1-span-4': 'Готовность через 2-3 недели',
      'language-price-description-1-span-5': 'Макияж, визаж',
      'language-price-description-2-span-1': 'Одна-две локации',
      'language-price-description-2-span-2': '200 цветных фото',
      'language-price-description-2-span-3': '20 отретушированных фото',
      'language-price-description-2-span-4': 'Готовность через 1-2 недели',
      'language-price-description-2-span-5': 'Макияж, визаж',
      'language-price-description-3-span-1': 'Три локации и больше',
      'language-price-description-3-span-2': '300 цветных фото',
      'language-price-description-3-span-3': '50 отретушированных фото',
      'language-price-description-3-span-4': 'Готовность через 1 неделю',
      'language-price-description-3-span-5': 'Макияж, визаж, прическа',
      'language-order': 'Заказать съемку',
      'language-contact-me': 'Свяжитесь со мной',
      'language-send-message': 'Отправить',
      'language-mail' : 'Эл. почта',
      'language-phone': 'Телефон',
      'language-message' : 'Сообщение',
    }
  }
 export default i18Obj;